### ISSUE TITLE
It seems I did everything right, but it starts, the lines run quickly and the utility closes, but program is not working.

### ISSUE THREAD

**Issue by jag983** [vsTerminus/Discord-NP#10]
![image](https://user-images.githubusercontent.com/18518893/51801221-fdb3be00-2264-11e9-813b-defddda02947.png)
What am I doing wrong?!..

**Comment by jag983** [comment]
Ok, solution is rename config.ini.example, to config.ini. Sorry.

**Comment by vsTerminus** [comment]
All good, glad you got it figured out :)
