### ISSUE TITLE
MacOS - client is not connected?

### ISSUE THREAD

**Issue by cosmicbutterfly** [vsTerminus/Discord-NP#18]
I'm pretty new to this and was trying to setup on MacOS Big Sur. My tokens validate ok, but it doesn't seem to be able to connect.

I edited out part of the path here but this is the error I'm getting. Any help would be appreciated.

$VAR1 = 'Cannot send OP - Client is not connected at /var/folders/v2/..../inc/lib/Mojo/Discord/Gateway.pm line 265.

(edit)
I also ran debug as mentioned by you in another ticket and this is what's in the log...

[2020-12-03 11:13:23.66829] [7563] [error] [Gateway.pm] [gateway] Could not retrieve Gateway URL from 'https://discord.com/api/gateway'
[2020-12-03 11:13:23.66862] [7563] [debug] $error = {
           'message' => 'IO::Socket::SSL 2.009+ required for TLS support'
         };

**Comment by vsTerminus** [comment]
Are you running from source? Or from the compiled binary?

If from source, try installing IO::Socket::SSL

`cpanm IO::Socket::SSL`

If from binary it's probably an issue with par packer not including something required for SSL and I'll need to look into it.

**Comment by vsTerminus** [comment]
As a followup thought, the Windows binary includes the OpenSSL binaries packaged with Perl... I wonder if macOS requires something similar. You could try installing OpenSSL on your Mac to see if that works?

```bash
brew install openssl
```

Let me know if any of that works and we'll go from there.

**Comment by cosmicbutterfly** [comment]
I'm running from the compiled binary. I installed openssl and am still getting the same error.

**Comment by vsTerminus** [comment]
Alright. Thanks for the info and for trying that out.

I'll have to figure out what's missing from the macOS binary and then upload a new version.

In the meantime, if you're so inclined, you could try running it from source. The steps are in the readme.

If you go that route, let me know if you have any trouble with setup so I can improve the docs.

**Comment by vsTerminus** [comment]
Please try https://github.com/vsTerminus/Discord-NP/releases/tag/1.4 - This build includes the OpenSSL libraries and should solve the problem.

**Comment by vsTerminus** [comment]
https://github.com/vsTerminus/Discord-NP/releases/tag/1.5 is available with some improvements over 1.4, if you haven't tried yet please try this one instead.

**Comment by vsTerminus** [comment]
Feel free to re open if this is not working still.
