### ISSUE TITLE
Tracks not getting picked up annd not showing

### ISSUE THREAD

**Issue by Matias314** [vsTerminus/Discord-NP#20]
Hello, I tried to run the Windows binary and it seems to connect and everything but my tracks are not showing and it doesn't seem to do much more than this.
![WindowsTerminal_LRu3wfVClu](https://user-images.githubusercontent.com/11633814/109232303-68c77a00-77c8-11eb-9bc7-8073b49f7ac3.png)

**Comment by vsTerminus** [comment]
That's strange. When you listen to music does it show up on your Last.FM page as "Scrobbling Now"?

![scrobbling now](https://user-images.githubusercontent.com/226622/109418976-a4ad3b80-7990-11eb-82bd-4cb844e6620b.PNG)

If they always just say "X minutes ago" then it's your scrobbler not sending the songs as currently playing, which is what the script is looking for.

You can try editing "config.ini": Set `log_level = debug` and save the file, then run it again. Wait a few seconds after it says "Connected to Discord" and then open "mojo-discord.log".

**Do not share the raw contents of this log** - it contains your entire Discord token. I will remove that in a future version.

It should look something like this: (I deleted my token from the logfile)

![mojo-discord-log](https://user-images.githubusercontent.com/226622/109419321-70d31580-7992-11eb-8985-f8aec432f4d3.PNG)

Specifically you should see `[dispatch_ready] Discord gateway is ready` if Discord is connected, and then if it's finding your music properly `[send_op] Sent: ` with the details of whatever you are listening to, and then `[debug] SESSIONS_REPLACE payload:` to tell you it's updating your presence status in Discord.

If yours looks different than this, please let me know and we can figure it out.

**Comment by Matias314** [comment]
Turns out my scrobbler did not report tracks as currently playing, resolved that and it's working now. Thanks a lot!
