### ISSUE TITLE
Mojo::Discord

### ISSUE THREAD

**Issue by hxck** [vsTerminus/Discord-NP#23]
Getting an error when I run this in Windows 10. I installed Strawberry Perl and used CPAN to install Config::Tiny, the strictures module, and Mojo::WebService::LastFM module without error. When trying to run I get this:

```
C:\Users\ccslo\Desktop\dnp>discordnp.pl
Can't locate Mojo/Discord.pm in @INC (you may need to install the Mojo::Discord module) (@INC contains: C:/Users/ccslo/Desktop/dnp/lib C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at C:/Users/ccslo/Desktop/dnp/lib/Discord/NP.pm line 8.
BEGIN failed--compilation aborted at C:/Users/ccslo/Desktop/dnp/lib/Discord/NP.pm line 8.
Compilation failed in require at C:\Users\ccslo\Desktop\dnp\discordnp.pl line 31.
BEGIN failed--compilation aborted at C:\Users\ccslo\Desktop\dnp\discordnp.pl line 31.
```

When trying to install, I get this:

```
cpan> install Mojo::Discord
Warning: Cannot install Mojo::Discord, don't know what it is.
Try the command

    i /Mojo::Discord/

to find objects with matching identifiers.
```

Any ideas?

**Comment by incognico** [comment]
Mojo-Discord is not on cpan, grab it here https://github.com/vsTerminus/Mojo-Discord

**Comment by vsTerminus** [comment]
Steps are in the readme, but yes. You'll want to grab a copy of Mojo::Discord from the link above and then

- Extract it to a folder somewhere
- Open it up, go into Mojo-Discord\lib\Mojo\
- Copy both Discord.pm and the Discord folder and paste them Strawberry Perl's vendor lib folder
  - Should be something like C:\Strawberry\perl\vendor\lib\Mojo\

Then try again.
