### ISSUE TITLE
Can't use an undefined value as a HASH reference.

### ISSUE THREAD

**Issue by deathspawn** [vsTerminus/Discord-NP#3]
I keep getting an error when I try to run the script.

`Can't use an undefined value as a HASH reference at /usr/lib/perl5/vendor_perl/Net/Discord/Gateway.pm line 149.`

Not sure if I have the token correct. I couldn't get it when I tried ctrl+shift+I so I tried making a bot user instead.

**Comment by vsTerminus** [comment]
Authentication is a little different for a Bot user, and this script isn't configured to identify itself that way. I'll keep that in mind for a future update though.

ctrl + shift + I might not work if you're using Discord in your browser. Try hitting F12 instead. 

You can also use the Desktop app, which definitely supports Ctrl + Shift + I.

**Comment by deathspawn** [comment]
Yeah, I tried doing it in the app on both Win10 and Linux. Both show an inspect element sidebar. Not sure where to type for the find. I tried the filter box but found nothing. A screenshot would be helpful.

**Comment by vsTerminus** [comment]
You should be able to type into the very bottom of the sidebar. Just click on the very bottom line and you should get a cursor. I don't have a functional Windows computer right now to show you a screenshot, but I can get one for you in a few days if you haven't figured it out by then.

If you do it in a browser, you would type into the Console tab of the inspector window.

Edit: Here's where you enter it in the desktop app sidebar. Copy the result without any quotes and paste that into the config.

![Discord Desktop App Screenshot](https://cloud.githubusercontent.com/assets/226622/20532034/312462ac-b09e-11e6-90da-dec342b9352c.png)

**Comment by deathspawn** [comment]
Thanks for the screenshot. Was trying to type in the wrong tab heh. I am still getting the undefined hash error. I believe it is an Arch issue though, but I'm not sure. I tried setting up the script on a Debian server and it seems to work, however it doesn't update my status at all (despite showing in the debug that it is and has connected/authenticated to Discord successfully.)

Also, might want to specify in the config.ini.example to not include the quotes around the token as that will cough up an error of 4004 authentication failed.

**Comment by vsTerminus** [comment]
Weird. I am running mine on Arch. 

As for status not updating, it *is*, but Discord won't send you your own status events, so there is no way for the official client to know. Ask your friend and they will see your status. Only you won't.

**Comment by deathspawn** [comment]
That's weird it doesn't show locally. Just queried my Red bot and it shows my status. Anyways, thanks for the help. Greatly appreciated.
