### ISSUE TITLE
Can't use an undefined value as a HASH reference at Net/Discord/Gateway.pm line 151.

### ISSUE THREAD

**Issue by alexdougie** [vsTerminus/Discord-NP#4]
Trying to run on Win 10 64 bit.

**Comment by vsTerminus** [comment]
This is usually a config or a network problem.

1. Are you behind any sort of proxy or restrictive firewall that might prevent you from connecting the bot to Discord?

2. Does your config look like this? ![https://i.imgur.com/lMiIx9N.png](https://i.imgur.com/lMiIx9N.png)

In particular, 

- no quotes around the Last.FM API Key
- no quotes around the Discord Token
- no quotes around any of the values

3. Are you trying to run the .pl script or the compiled .exe version? In either case, it might be helpful to install [Strawberry Perl](http://strawberryperl.com/) if you haven't already.

**Comment by vsTerminus** [comment]
This has been untouched with no new info since February, so I am closing it. Please feel free to re-open if you are still having trouble.
