### ISSUE TITLE
Android notifications not working when using the script

### ISSUE THREAD

**Issue by eWU6yS6F** [vsTerminus/Discord-NP#5]
As above, whenever the script is running I no longer receive android notifications, stop the script and everything works as it should.

is this a limitation, and expected behaviour, or should push notifications work as intended?

**Comment by vsTerminus** [comment]
Well, I was wondering why my Android notifications weren't working so I guess that explains it.

I'll have to modify this so that it only connects to Discord to update your status, and then have it immediately disconnect. That should solve the notifications problem.

**Comment by vsTerminus** [comment]
This is fixed as of 77a88aeed693f5854f4f17121f5037a2f7abb724

The script now connects only when a new song has been detected from Last.FM, and immediately disconnects after setting the status.

I have been running this build for a couple weeks now and my notifications seem to be working perfectly.

It should still be compatible with the current version of Mojo::Discord, but please let me know if you run into issues and I will push an update for that too.
