### ISSUE TITLE
No status Change even tho appears to be working on the console

### ISSUE THREAD

**Issue by aenertia** [vsTerminus/Discord-NP#6]
Last.fm is getting queried and I see the correct track being dumped out in the terminal - and a message saying connected to Discord so am assuming the token is correct - but I get no status updated to the Last-fm track. 

Ubuntu 17.04, Discord 30/03/2017 - Linux

**Comment by aenertia** [comment]
Output e.g:

aenertia@kiorewha:~/build/Discord-NP$ ./discordnp.pl 
Mon Apr 17 13:40:15 2017 - Loaded Config: config.ini
Mon Apr 17 13:40:17 2017 - Connected to Discord.
Mon Apr 17 13:40:18 2017 - Status Updated: Lacuna Coil - In Visible Light

**Comment by aenertia** [comment]
![screenshot from 2017-04-17 13-41-57](https://cloud.githubusercontent.com/assets/286383/25076295/b170bd28-2373-11e7-834b-f487c2d98e5e.png)

**Comment by vsTerminus** [comment]
Sadly, the Discord API does not send you your own status updates. Basically, this means the desktop client is not aware that you have set anything, so it will show your status as empty. Sorry - Nothing I can do until they change how this works in the backend.

If you want to check that it's working for sure, ask a friend to tell you what your status message is. Some bots can also display it for you (mine cannot yet).

Feel free to re-open this if other users are seeing an empty status. The script output looks good to me, it should be working properly.

**Comment by aenertia** [comment]
Ahh - perfect. Might want to add the readme

**Comment by vsTerminus** [comment]
It's already in the readme, but I can make it more obvious.

**Comment by aenertia** [comment]
**facepalm** sorry.
