### ISSUE TITLE
Thank you; and sorry for bug tracker

### ISSUE THREAD

**Issue by Shadow19231** [vsTerminus/Discord-NP#9]
I want to apologize for commenting through your bug tracker, however I could not find a single way to message you formally. 

I just wanted to say thank you for this amazing plugin. I run it with itunes and it allows me to show my friends what i listen to , because we like to go back and fourth with bands. 

I'm sure all of us really appreciate your work.

**Comment by vsTerminus** [comment]
Thank you for your kind words. Apologies for taking 100 years to respond.
